export default types = {
    FETCH_TRENDING_PHOTOS : 'FETCH_TRENDING_PHOTOS',
    FETCHING_REQUEST: 'FETCHING_REQUEST',
    FETCHING_SUCCESS: 'FETCHING_SUCCESS',
    FETCHING_FAILED: 'FETCHING_FAILED',
    FAVOURITE_ITEM: 'FAVOURITE_ITEM'
}